trigger: none
pr: none

variables:
  ROSWIN_COLCON_BUILD_WORKING_DIRECTORY: $(Build.SourcesDirectory)\ros-colcon-build

jobs:
- job: Build
  timeoutInMinutes: 300
  pool:
    vmImage: 'vs2017-win2016'
  variables:
    ROSWIN_ROSDEP_LIST_URI: 'https://raw.githubusercontent.com/ms-iot/rosdistro-db/init_windows_py37/rosdep/sources.list.d/10-ms-iot.list'
    ROSWIN_METAPACKAGE: 'ALL'
    ROSWIN_VSTOOL: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat'
    ROSWIN_CMAKE_INSTALL_PREFIX: 'c:/opt/ros/dashing/x64'
    ROSWIN_ADDITIONAL_PACKAGE: 'ros_rosdeps'
    ROS_DISTRO: 'dashing'
    ROS_ETC_DIR: 'c:\opt\ros\dashing\x64\etc\ros'
    BUILD_TOOL_PACKAGE: 'ros-colcon-tools'
    PYTHON_LOCATION: 'c:\opt\python37amd64'
  strategy:
    matrix:
      dashing-ros_core:
        ROSWIN_METAPACKAGE: 'ros_core'
      dashing-ros_base:
        ROSWIN_METAPACKAGE: 'ros_base'
      dashing-desktop:
        ROSWIN_METAPACKAGE: 'desktop'
      # dashing-ALL:
      #   ROSWIN_PACKAGE_SKIP: 'apriltag behaviortree_cpp_v3 cartographer gazebo_ros ros_workspace'
  steps:
  # - template: ..\common\agent-clean.yml
  - template: ..\common\checkout.yml
  - template: ..\common\build.yml
  - template: ..\..\package-build\package-build.yml
- job: TestInstall
  dependsOn: Build
  strategy:
    matrix:
      dashing-ros_core:
        ROS_DISTRO: 'dashing'
        ROSWIN_METAPACKAGE: 'ros_core'
  timeoutInMinutes: 300
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - template: ..\..\package-build\package-test.yml
